### ISSUE TITLE
build destination

### ISSUE THREAD

**Issue by nothingismagick** [anuejn/axiom_touch_mock#1]
Is it possible for you to push a build folder / or at least give some vetted instructions about how to build properly?

Thanks

**Comment by anuejn** [comment]
there is no build process :)
just git clone --recursive and serve this directory via a local webserver.
however, you can also look at it at https://anuejn.github.io/axiom_touch_mock/

**Comment by nothingismagick** [comment]
![screen shot 2018-03-02 at 11 42 09](https://user-images.githubusercontent.com/35242872/36895346-da4b0b72-1e0e-11e8-8afc-92894b69de0c.png)

**Comment by nothingismagick** [comment]
ok - just saw your --recursive flag

**Comment by nothingismagick** [comment]
still, it would be good of you to include a License file and README with that info.

**Comment by nothingismagick** [comment]
And I am really unsure why swiper is so huge! 49.2 MB is a lot to download, if you are pinning it to a release maybe it makes sense to fork that release and flatten it to evade the changelist (which is probably why it is so HUGE) - alternatively why not just use node and build it with npm / yarn?

But maybe I don't understand the purpose of this project and you are just experimenting with interaction methodologies...

**Comment by anuejn** [comment]
> you are just experimenting with interaction methodologies...

Thats exactly, whats the pupose of this repo: Showing, that there are nicer ways to interact with a camera on touchscreen interfaces, than the ux we are currently prototyping.

Therfore the technology behind this is quite quick and dirty (as you already observed but didnt dare to say ;)). Including a Readme and a license is nice anyways... will do :)

**Comment by nothingismagick** [comment]
So tell me what are your thoughts? I personally agree that the sliders should be brought back into the selection process and also that there are some parts that don't need sliders and that everything should be on one page (with pop-in context if necessary).

**Comment by anuejn** [comment]
sorry for late reply. 
my sliders actually behave quite ugly (no back bounce/ not realistic physical simulation), but i also think, that they are a nice design pattern.
you are right: maybe we need some additional components (ie. for stats, recording state, ...), but i would like to try to stick mostly with sliders :)
