### ISSUE TITLE
Design Spec

### ISSUE THREAD

**Issue by nothingismagick** [anuejn/axiom_touch_mock#2]
The interaction is smooth, which is nice, however I am confused because it doesn't seem to follow the design spec - that I understood to be this:

http://files.apertus.org/AXIOM-Beta/AXIOM-WebRemote/

Is there a conversation that I don't know about?

**Comment by anuejn** [comment]
This repo is just another mockup proposal, which hadnt much engagement by apertus. It isnt following the current design concept - it is suggesting something new. However, sebastien pointed out, that not every parameter is representable as a 1D slider.

**Comment by nothingismagick** [comment]
ok - i see.
